name: windscribe-proxy
version: '1.0.0'
summary: Standalone Windscribe proxies client.
description: |
  Standalone Windscribe proxies client. Just run it and it'll start plain HTTP proxy server forwarding traffic via proxies of your choice.

confinement: strict
base: core18

parts:
  windscribe-proxy:
    plugin: go
    source: .
    build-packages:
      - gcc
    override-build:
      make &&
      cp bin/windscribe-proxy "$SNAPCRAFT_PART_INSTALL"
    stage:
      - windscribe-proxy

apps:
  windscribe-proxy:
    command: windscribe-proxy
    plugs:
      - network
      - network-bind
